"""Content for the DM Assignment-1 handwriting sheets.

Every entry is a block. build.py costs each block in ruled lines, paginates at
LINES_PER_SHEET, and refuses to build if a line of text is wider than the
writing area. Keep prose lines to roughly seven words.

Block forms:
    ("q",     "Question 3.4")            heading, 1 line, bold
    ("ln",    "text")                    one ruled line
    ("ind",   "text")                    indented one step
    ("ind2",  "text")                    indented two steps
    ("math",  "a(P1) = (2 + 4) / 2 = 3") monospace, 1 line
    ("quote", "text")                    serif, the textbook's wording
    ("blank",)                           one empty rule
    ("table", [headers], [[cells]], "llr")   1 header + n body rows
    ("draw",  "What to draw", ["line", ...])  a dashed instruction box
"""

TITLE = "Data Mining Assignment-1 — worked solutions"
COURSE = "CSE 4333 · Han, Pei & Tong 4th ed. · Chapters 3, 4, 6, 8"
BLURB = (
    "The exam is Wednesday 7 October. Part B is the revision half — start there. "
    "Part A holds the eight assignment solutions as F4 sheets to copy by hand "
    "for the 28 October submission."
)
DATES = [
    ("Final exam", "Wed 7 October, 2:00–5:00 PM",
     "CSE 4333(V4), 3 hours — Chapters 3, 4, 6 and 8, one question from each"),
    ("Assignment-1 due", "28 October",
     "handwritten, to the Section Office, 1–2 days' grace"),
]

SHEETS_INTRO = (
    "Copy straight down. Each sheet below is one F4 page at 32 ruled lines, "
    "so if a sheet ends mid-answer the next one picks it up. Diagrams are "
    "drawn out in full \u2014 copy them exactly as they appear."
)

# --------------------------------------------------------------------------
# Chapter 3 — Data warehousing and OLAP
# --------------------------------------------------------------------------

BLOCKS = [

    # ===================== 3.4 =====================
    ("q", "Problem 3.4"),
    ("quote", "Warehouse of three dimensions time, doctor"),
    ("quote", "and patient, with measures count and charge,"),
    ("quote", "where charge is the fee a doctor charges a"),
    ("quote", "patient for a visit."),
    ("blank",),

    ("quote", "(a) Enumerate three classes of schemas that are popularly used for modeling data warehouses."),
    ("blank",),
    ("ln", "Three schema classes used to model"),
    ("ln", "data warehouses:"),
    ("ind", "1. Star schema — one fact table, each"),
    ("ind2", "dimension a single flat table."),
    ("ind", "2. Snowflake schema — dimensions are"),
    ("ind2", "normalised into sub-tables."),
    ("ind", "3. Fact constellation — several fact"),
    ("ind2", "tables sharing dimension tables."),
    ("blank",),

    ("quote", "(b) Draw a schema diagram for the above data warehouse using one of the schema classes listed in (a)."),
    ("blank",),
    ("ln", "Star schema for this warehouse."),
    ("ln", "Fact table and three dimensions:"),
    ("blank",),
        ("svg", "star_doctor"),
    ("blank",),
    ("ln", "fee (fact table)"),
    ("ind", "time_key, doctor_id, patient_id,"),
    ("ind", "count, charge"),
    ("ln", "time (dimension)"),
    ("ind", "time_key, day, day_of_week, month,"),
    ("ind", "quarter, year"),
    ("ln", "doctor (dimension)"),
    ("ind", "doctor_id, name, phone, address,"),
    ("ind", "specialty"),
    ("ln", "patient (dimension)"),
    ("ind", "patient_id, name, address, phone,"),
    ("ind", "gender"),
    ("blank",),

    ("quote", "(c) Starting with the base cuboid [day, doctor, patient], what specific OLAP operations should be performed in order to list the total fee collected by each doctor in 2010?"),
    ("blank",),
    ("ln", "Starting from the base cuboid"),
    ("ln", "[day, doctor, patient], to list the total"),
    ("ln", "fee collected by each doctor in 2010:"),
    ("ind", "1. Roll-up on time, from day to year."),
    ("ind", "2. Slice on time, keeping year = 2010."),
    ("ind", "3. Roll-up on patient, up to all, so"),
    ("ind2", "charge is summed over all patients."),
    ("blank",),
    ("ln", "The result is the cuboid"),
    ("ln", "[year = 2010, doctor, all] holding"),
    ("ln", "sum(charge) for each doctor."),
    ("blank",),

    # ===================== 3.5 =====================
    ("q", "Problem 3.5"),
    ("quote", "Big_University warehouse of four dimensions"),
    ("quote", "student, course, semester and instructor,"),
    ("quote", "with measures count and avg_grade. At the"),
    ("quote", "lowest level avg_grade is the actual course"),
    ("quote", "grade; higher up it is an average."),
    ("blank",),

    ("quote", "(a) Draw a snowflake schema diagram for the data warehouse."),
    ("blank",),
    ("ln", "Snowflake schema. The dimensions are"),
    ("ln", "normalised, so each one splits into"),
    ("ln", "further tables:"),
    ("blank",),
        ("svg", "snowflake_university"),
    ("blank",),
    ("ln", "university (fact table)"),
    ("ind", "student_id, course_id, semester_id,"),
    ("ind", "instructor_id, count, avg_grade"),
    ("ln", "student → major"),
    ("ind", "student_id, name, major_id, status"),
    ("ind", "major_id, major_name, university"),
    ("ln", "course → department"),
    ("ind", "course_id, course_name, dept_id"),
    ("ind", "dept_id, dept_name, college"),
    ("ln", "semester"),
    ("ind", "semester_id, semester, year"),
    ("ln", "instructor → department"),
    ("ind", "instructor_id, name, dept_id"),
    ("blank",),

    ("quote", "(b) Starting with the base cuboid [student, course, semester, instructor], what specific OLAP operations should you perform in order to list the average grade of CS courses for each Big_University student?"),
    ("blank",),
    ("ln", "From the base cuboid [student, course,"),
    ("ln", "semester, instructor], to list the average"),
    ("ln", "grade of CS courses per student:"),
    ("ind", "1. Roll-up on course, from course_id"),
    ("ind2", "to department."),
    ("ind", "2. Dice on department = \"CS\" and"),
    ("ind2", "university = \"Big_University\"."),
    ("ind", "3. Roll-up on semester, up to all."),
    ("ind", "4. Roll-up on instructor, up to all."),
    ("blank",),
    ("ln", "The result is [student, CS, all, all]"),
    ("ln", "holding avg_grade for each student."),
    ("blank",),
    ("ln", "Note avg_grade is algebraic, not"),
    ("ln", "distributive: to roll it up you must keep"),
    ("ln", "sum and count, then divide. Averaging the"),
    ("ln", "averages would give the wrong answer."),
    ("blank",),

    ("quote", "(c) If each dimension has five levels (including all), such as student < major < status < university < all, how many cuboids will this cube contain, including the base and apex cuboids?"),
    ("blank",),
    ("ln", "Every dimension has five levels,"),
    ("ln", "counting all. With four dimensions the"),
    ("ln", "number of cuboids is the product of the"),
    ("ln", "level counts:"),
    ("blank",),
    ("math", "cuboids = 5 x 5 x 5 x 5 = 5^4"),
    ("math", "        = 625"),
    ("blank",),
    ("ln", "So 625 cuboids, and that total already"),
    ("ln", "includes the base cuboid and the apex"),
    ("ln", "cuboid."),

    # ===================== 3.6 =====================
    ("q", "Problem 3.6"),
    ("quote", "Warehouse of four dimensions date,"),
    ("quote", "spectator, location and game, with measures"),
    ("quote", "count and charge. Spectators may be"),
    ("quote", "students, adults or seniors, each category"),
    ("quote", "having its own charge rate."),
    ("blank",),

    ("quote", "(a) Draw a star schema diagram for the data warehouse."),
    ("blank",),
    ("ln", "Star schema. One fact table and four"),
    ("ln", "flat dimension tables:"),
    ("blank",),
        ("svg", "star_spectator"),
    ("blank",),
    ("ln", "sales (fact table)"),
    ("ind", "date_key, spectator_id, location_id,"),
    ("ind", "game_id, count, charge"),
    ("ln", "date (dimension)"),
    ("ind", "date_key, day, month, quarter, year"),
    ("ln", "spectator (dimension)"),
    ("ind", "spectator_id, name, category,"),
    ("ind", "phone, address"),
    ("ln", "location (dimension)"),
    ("ind", "location_id, name, street, city,"),
    ("ind", "province, country"),
    ("ln", "game (dimension)"),
    ("ind", "game_id, name, description, type"),
    ("blank",),

    ("quote", "(b) Starting with the base cuboid [date, spectator, location, game], what specific OLAP operations should you perform in order to list the total charge paid by student spectators at GM_Place in 2010?"),
    ("blank",),
    ("ln", "From the base cuboid [date, spectator,"),
    ("ln", "location, game], to list the total charge"),
    ("ln", "paid by student spectators at GM_Place"),
    ("ln", "in 2010:"),
    ("ind", "1. Roll-up on date, from date_key to"),
    ("ind2", "year."),
    ("ind", "2. Roll-up on spectator, from"),
    ("ind2", "spectator_id to category."),
    ("ind", "3. Dice with year = 2010,"),
    ("ind2", "category = \"student\" and"),
    ("ind2", "location name = \"GM_Place\"."),
    ("ind", "4. Roll-up on game, up to all."),
    ("blank",),
    ("ln", "The single value left is sum(charge) for"),
    ("ln", "student spectators at GM_Place in 2010."),

    # ===================== 4.6 (a) =====================
    ("q", "Problem 4.6 (a)"),
    ("quote", "Five transactions, with min_sup = 60% and"),
    ("quote", "min_conf = 80%. Find all frequent itemsets"),
    ("quote", "using Apriori and FP-growth, and compare"),
    ("quote", "the efficiency of the two."),
    ("blank",),
    ("table",
     ["TID", "items_bought"],
     [["T100", "M, O, N, K, E, Y"],
      ["T200", "D, O, N, K, E, Y"],
      ["T300", "M, A, K, E"],
      ["T400", "M, U, C, K, Y"],
      ["T500", "C, O, O, K, I, E"]],
     "ll"),
    ("blank",),
    ("blank",),

    ("ln", "APRIORI"),
    ("ln", "Scan 1 - count every single item:"),
    ("table",
     ["item", "count", "item", "count"],
     [["K", "5", "N", "2"],
      ["E", "4", "C", "2"],
      ["M", "3", "D", "1"],
      ["O", "3", "A", "1"],
      ["Y", "3", "U, I", "1"]],
     "lrlr"),
    ("ln", "L1 = {K}, {E}, {M}, {O}, {Y}"),
    ("blank",),
    ("ln", "Scan 2 - count the ten pairs from L1:"),
    ("table",
     ["pair", "count", "pair", "count"],
     [["KE", "4", "ME", "2"],
      ["MK", "3", "MY", "2"],
      ["OK", "3", "OY", "2"],
      ["OE", "3", "EY", "2"],
      ["KY", "3", "MO", "1"]],
     "lrlr"),
    ("ln", "L2 = {K,E}, {M,K}, {O,K}, {O,E}, {K,Y}"),
    ("blank",),
    ("ln", "Scan 3 - join L2, prune by the Apriori"),
    ("ln", "property:"),
    ("ind", "{K,M,O} needs {M,O}, count 1 - pruned"),
    ("ind", "{K,M,Y} needs {M,Y}, count 2 - pruned"),
    ("ind", "{K,O,Y} needs {O,Y}, count 2 - pruned"),
    ("ind", "{E,K,O} - all subsets frequent, kept"),
    ("ln", "Count {E,K,O}: T100, T200, T500 = 3"),
    ("ln", "L3 = {E,K,O}"),
    ("blank",),
    ("ln", "11 frequent itemsets in total:"),
    ("ind", "size 1: K:5, E:4, M:3, O:3, Y:3"),
    ("ind", "size 2: KE:4, MK:3, OK:3, OE:3, KY:3"),
    ("ind", "size 3: EKO:3"),
    ("blank",),

    ("ln", "FP-GROWTH"),
    ("ln", "Order items by falling count:"),
    ("ln", "K:5, E:4, M:3, O:3, Y:3"),
    ("ln", "Drop infrequent items and reorder each"),
    ("ln", "transaction:"),
    ("table",
     ["TID", "ordered frequent items"],
     [["T100", "K, E, M, O, Y"],
      ["T200", "K, E, O, Y"],
      ["T300", "K, E, M"],
      ["T400", "K, M, Y"],
      ["T500", "K, E, O"]],
     "ll"),
    ("blank",),
        ("svg", "fp_tree"),
    ("blank",),
    ("table",
     ["item", "conditional pattern base", "gives"],
     [["Y", "{K,E,M,O}:1 {K,E,O}:1 {K,M}:1", "KY:3"],
      ["O", "{K,E,M}:1  {K,E}:2", "KO, EO, KEO"],
      ["M", "{K,E}:2  {K}:1", "KM:3"],
      ["E", "{K}:4", "KE:4"]],
     "lll"),
    ("blank",),

    ("ln", "COMPARING THE TWO"),
    ("ind", "Apriori scanned the database 4 times;"),
    ("ind2", "FP-growth scans it twice."),
    ("ind", "Apriori built 10 candidate pairs and"),
    ("ind2", "5 of them were not frequent."),
    ("ind", "FP-growth generates no candidates at"),
    ("ind2", "all; it grows patterns from the tree."),

    # ===================== 6.7 =====================
    ("q", "Problem 6.7"),
    ("quote", "Generalised training data from an employee"),
    ("quote", "database. count is the number of tuples"),
    ("quote", "with those values. The class label is"),
    ("quote", "status."),
    ("blank",),
    ("table",
     ["dept", "status", "age", "salary", "n"],
     [["sales", "senior", "31-35", "46-50K", "30"],
      ["sales", "junior", "26-30", "26-30K", "40"],
      ["sales", "junior", "31-35", "31-35K", "40"],
      ["systems", "junior", "21-25", "46-50K", "20"],
      ["systems", "senior", "31-35", "66-70K", "5"],
      ["systems", "junior", "26-30", "46-50K", "3"],
      ["systems", "senior", "41-45", "66-70K", "3"],
      ["marketing", "senior", "36-40", "46-50K", "10"],
      ["marketing", "junior", "31-35", "41-45K", "4"],
      ["secretary", "senior", "46-50", "36-40K", "4"],
      ["secretary", "junior", "26-30", "26-30K", "6"]],
     "llllr"),
    ("blank",),
    ("ln", "Total 165 tuples: senior 52, junior 113."),

    ("h", "Problem 6.7 (a)"),
    ("quote", "(a) How would you modify the basic decision tree algorithm to take into consideration the count of each generalized data tuple, that is, of each row entry?"),
    ("blank",),
    ("ln", "Taking count into account."),
    ("blank",),
    ("ln", "Each row stands for count identical"),
    ("ln", "tuples, so everywhere the basic algorithm"),
    ("ln", "adds 1 for a tuple, add that row's count"),
    ("ln", "instead. Concretely:"),
    ("ind", "|D| becomes the sum of all counts."),
    ("ind", "The frequency of class Ci is the sum"),
    ("ind2", "of counts of rows in that class."),
    ("ind", "Info(D), InfoA(D), SplitInfo and Gini"),
    ("ind2", "all use these weighted sums."),
    ("ind", "A node is pure when every row in it"),
    ("ind2", "carries the same class label."),
    ("blank",),

    ("h", "Problem 6.7 (b)"),
    ("quote", "(b) Use your algorithm to construct a decision tree from the given data."),
    ("blank",),
    ("ln", "Building the tree. Expected"),
    ("ln", "information for the whole set:"),
    ("math", "Info(D) = -(52/165)log2(52/165)"),
    ("math", "          -(113/165)log2(113/165)"),
    ("math", "        = 0.5250 + 0.3740 = 0.8990"),
    ("blank",),
    ("ln", "Splitting on department:"),
    ("table",
     ["branch", "n", "sen", "jun", "Info"],
     [["sales", "110", "30", "80", "0.8454"],
      ["systems", "31", "8", "23", "0.8238"],
      ["marketing", "14", "10", "4", "0.8631"],
      ["secretary", "10", "4", "6", "0.9710"]],
     "lrrrr"),
    ("math", "Info_dept(D) = 0.8504"),
    ("math", "Gain(department) = 0.0486"),
    ("blank",),
    ("ln", "Splitting on age. Only 31-35 is mixed;"),
    ("ln", "every other age group is pure."),
    ("table",
     ["branch", "n", "sen", "jun", "Info"],
     [["21-25", "20", "0", "20", "0"],
      ["26-30", "49", "0", "49", "0"],
      ["31-35", "79", "35", "44", "0.9906"],
      ["36-40, 41-45, 46-50", "17", "17", "0", "0"]],
     "lrrrr"),
    ("math", "Info_age(D) = (79/165)(0.9906) = 0.4743"),
    ("math", "Gain(age) = 0.4247"),
    ("blank",),
    ("ln", "Splitting on salary. Only 46-50K mixed:"),
    ("table",
     ["branch", "n", "sen", "jun", "Info"],
     [["26-30K", "46", "0", "46", "0"],
      ["31-35K", "40", "0", "40", "0"],
      ["36-40K", "4", "4", "0", "0"],
      ["41-45K", "4", "0", "4", "0"],
      ["46-50K", "63", "40", "23", "0.9468"],
      ["66-70K", "8", "8", "0", "0"]],
     "lrrrr"),
    ("math", "Info_sal(D) = (63/165)(0.9468) = 0.3615"),
    ("math", "Gain(salary) = 0.5375"),

    ("h", "Problem 6.7 (b) continued"),
    ("ln", "Salary has the largest gain, so it is"),
    ("ln", "the root:"),
    ("math", "salary 0.5375 > age 0.4247"),
    ("math", "       > department 0.0486"),
    ("blank",),
        ("svg", "decision_tree"),

    ("h", "Problem 6.7 (c)"),
    ("quote", "(c) Given a data tuple having the values systems, 26...30 and 46-50K for the attributes department, age and salary respectively, what would a naive Bayesian classification of the status for the tuple be?"),
    ("blank",),
    ("ln", "Naive Bayes for the tuple"),
    ("ln", "X = (systems, 26-30, 46-50K)."),
    ("blank",),
    ("math", "P(senior) = 52/165  = 0.3152"),
    ("math", "P(junior) = 113/165 = 0.6849"),
    ("blank",),
    ("ln", "Conditional probabilities for senior:"),
    ("math", "P(systems | senior) =  8/52 = 0.1538"),
    ("math", "P(26-30  | senior) =  0/52 = 0"),
    ("math", "P(46-50K | senior) = 40/52 = 0.7692"),
    ("math", "P(X | senior) = 0"),
    ("blank",),
    ("ln", "Conditional probabilities for junior:"),
    ("math", "P(systems | junior) = 23/113 = 0.2035"),
    ("math", "P(26-30  | junior) = 49/113 = 0.4336"),
    ("math", "P(46-50K | junior) = 23/113 = 0.2035"),
    ("math", "P(X | junior) = 0.2035 x 0.4336"),
    ("math", "                x 0.2035 = 0.01796"),
    ("blank",),
    ("math", "P(X|senior)P(senior) = 0"),
    ("math", "P(X|junior)P(junior) = 0.01796 x 0.6849"),
    ("math", "                     = 0.01230"),
    ("blank",),
    ("ln", "The classifier predicts status = junior."),
    ("blank",),

    # ===================== 6.17 =====================
    ("q", "Problem 6.17"),
    ("quote", "The tuples of Fig. 6.28 are sorted by"),
    ("quote", "falling probability from a classifier."),
    ("quote", "Compute TP, FP, TN, FN, then TPR and FPR,"),
    ("quote", "and plot the ROC curve."),
    ("blank",),
    ("table",
     ["#", "cls", "prob", "TP", "FP", "TN", "FN", "TPR", "FPR"],
     [["1", "P", "0.95", "1", "0", "5", "4", "0.2", "0.0"],
      ["2", "N", "0.85", "1", "1", "4", "4", "0.2", "0.2"],
      ["3", "P", "0.78", "2", "1", "4", "3", "0.4", "0.2"],
      ["4", "P", "0.66", "3", "1", "4", "2", "0.6", "0.2"],
      ["5", "N", "0.60", "3", "2", "3", "2", "0.6", "0.4"],
      ["6", "P", "0.55", "4", "2", "3", "1", "0.8", "0.4"],
      ["7", "N", "0.53", "4", "3", "2", "1", "0.8", "0.6"],
      ["8", "N", "0.52", "4", "4", "1", "1", "0.8", "0.8"],
      ["9", "N", "0.51", "4", "5", "0", "1", "0.8", "1.0"],
      ["10", "P", "0.40", "5", "5", "0", "0", "1.0", "1.0"]],
     "llrrrrrrr"),

    ("h", "Problem 6.17 continued"),
    ("math", "TPR = TP / (TP + FN) = TP / 5"),
    ("math", "FPR = FP / (FP + TN) = FP / 5"),
    ("blank",),
        ("svg", "roc_curve"),
    ("blank",),
    ("ln", "Area under the curve, by rectangles of"),
    ("ln", "width 0.2:"),
    ("math", "AUC = 0.2(0.2) + 0.2(0.6) + 0.2(0.8)"),
    ("math", "      + 0.2(0.8) + 0.2(0.8)"),
    ("math", "    = 0.04 + 0.12 + 0.16 + 0.16 + 0.16"),
    ("math", "    = 0.64"),
    ("blank",),

    # ===================== 8.2 =====================
    ("q", "Problem 8.2"),
    ("quote", "Cluster eight points into three clusters"),
    ("quote", "by k-means, using Euclidean distance, with"),
    ("quote", "A1, B1 and C1 as the initial centres."),
    ("blank",),
    ("ln", "A1(2,10) A2(2,5)  A3(8,4) B1(5,8)"),
    ("ln", "B2(7,5)  B3(6,4)  C1(1,2) C2(4,9)"),
    ("blank",),
    ("table",
     ["point", "(2,10)", "(5,8)", "(1,2)", "cluster"],
     [["A1 (2,10)", "0", "3.61", "8.06", "1"],
      ["A2 (2,5)", "5.00", "4.24", "3.16", "3"],
      ["A3 (8,4)", "8.49", "5.00", "7.28", "2"],
      ["B1 (5,8)", "3.61", "0", "7.21", "2"],
      ["B2 (7,5)", "7.07", "3.61", "6.71", "2"],
      ["B3 (6,4)", "7.21", "4.12", "5.39", "2"],
      ["C1 (1,2)", "8.06", "6.71", "0", "3"],
      ["C2 (4,9)", "2.24", "1.41", "7.62", "2"]],
     "lrrrr"),

    ("h", "Problem 8.2 (a)"),
    ("quote", "(a) The three cluster centers after the first round of execution."),
    ("blank",),
    ("ln", "The clusters after round 1 are"),
    ("ind", "1: {A1}"),
    ("ind", "2: {A3, B1, B2, B3, C2}"),
    ("ind", "3: {A2, C1}"),
    ("blank",),
    ("ln", "New centres are the means of those:"),
    ("math", "m1 = (2, 10)"),
    ("math", "m2 = ((8+5+7+6+4)/5, (4+8+5+4+9)/5)"),
    ("math", "   = (30/5, 30/5) = (6, 6)"),
    ("math", "m3 = ((2+1)/2, (5+2)/2) = (1.5, 3.5)"),
    ("blank",),
    ("ln", "So the three centres after the first"),
    ("ln", "round of execution are"),
    ("math", "(2, 10)   (6, 6)   (1.5, 3.5)"),

    ("h", "Problem 8.2 (b)"),
    ("quote", "(b) The final three clusters."),
    ("blank",),
    ("ln", "ROUND 2, centres (2,10) (6,6) (1.5,3.5)."),
    ("ln", "C2 moves to cluster 1:"),
    ("ind", "1: {A1, C2}   2: {A3, B1, B2, B3}"),
    ("ind", "3: {A2, C1}"),
    ("math", "m1 = (3, 9.5)"),
    ("math", "m2 = (26/4, 21/4) = (6.5, 5.25)"),
    ("math", "m3 = (1.5, 3.5)"),
    ("blank",),
    ("ln", "ROUND 3, centres (3,9.5) (6.5,5.25)"),
    ("ln", "(1.5,3.5). B1 is now nearer centre 1:"),
    ("math", "B1 to m1 = 2.50,  B1 to m2 = 3.13"),
    ("ind", "1: {A1, B1, C2}  2: {A3, B2, B3}"),
    ("ind", "3: {A2, C1}"),
    ("math", "m1 = (11/3, 9)    = (3.67, 9)"),
    ("math", "m2 = (21/3, 13/3) = (7, 4.33)"),
    ("math", "m3 = (1.5, 3.5)"),
    ("blank",),
    ("table",
     ["cluster", "members", "centre"],
     [["1", "A1(2,10) B1(5,8) C2(4,9)", "(3.67, 9)"],
      ["2", "A3(8,4) B2(7,5) B3(6,4)", "(7, 4.33)"],
      ["3", "A2(2,5) C1(1,2)", "(1.5, 3.5)"]],
     "lll"),
    ("svg", "kmeans_plot"),

    # ===================== 8.17 =====================
    ("q", "Problem 8.17"),
    ("quote", "Describe k-means, k-medoids, BIRCH and"),
    ("quote", "DBSCAN in terms of the shapes of cluster"),
    ("quote", "they find, the input parameters they need,"),
    ("quote", "and their limitations."),
    ("blank",),
    ("ln", "(a) k-means"),
    ("ind", "Shapes: spherical and convex, of"),
    ("ind2", "roughly equal size."),
    ("ind", "Input: k, the number of clusters."),
    ("ind", "Limits: k must be known in advance;"),
    ("ind2", "the result depends on the initial"),
    ("ind2", "centres and may be a local optimum;"),
    ("ind2", "the mean is not robust, so outliers"),
    ("ind2", "drag centres; needs numeric data;"),
    ("ind2", "cannot find non-convex shapes."),
    ("blank",),
    ("ln", "(b) k-medoids, as in PAM"),
    ("ind", "Shapes: spherical and convex, as"),
    ("ind2", "with k-means."),
    ("ind", "Input: k."),
    ("ind", "Limits: far more robust to outliers,"),
    ("ind2", "because a medoid is an actual object"),
    ("ind2", "and it minimises absolute error, not"),
    ("ind2", "squared error; but each iteration"),
    ("ind2", "costs O(k(n-k)^2), so it does not"),
    ("ind2", "scale; k is still needed; still poor"),
    ("ind2", "on non-convex shapes."),

    ("h", "Problem 8.17 continued"),
    ("ln", "(c) BIRCH"),
    ("ind", "Shapes: spherical, because a cluster"),
    ("ind2", "is summarised by a CF triple and"),
    ("ind2", "judged by its radius and diameter."),
    ("ind", "Input: branching factor B and"),
    ("ind2", "threshold T for the CF tree, plus"),
    ("ind2", "available memory, and k if the"),
    ("ind2", "optional global clustering runs."),
    ("ind", "Limits: numeric data only; the result"),
    ("ind2", "depends on the order the data"),
    ("ind2", "arrives in; sensitive to T; poor on"),
    ("ind2", "non-spherical shapes. In exchange it"),
    ("ind2", "needs one scan and is incremental."),
    ("blank",),
    ("ln", "(d) DBSCAN"),
    ("ind", "Shapes: arbitrary. Any density"),
    ("ind2", "connected shape, convex or not, and"),
    ("ind2", "it labels outliers as noise."),
    ("ind", "Input: Eps, the radius, and MinPts,"),
    ("ind2", "the least neighbours for a core"),
    ("ind2", "point. Note that k is not required."),
    ("ind", "Limits: one global Eps and MinPts"),
    ("ind2", "cannot suit clusters of widely"),
    ("ind2", "different density; the result is"),
    ("ind2", "sensitive to both; distances lose"),
    ("ind2", "meaning in high dimensions; cost is"),
    ("ind2", "O(n^2) without a spatial index, and"),
    ("ind2", "O(n log n) with one."),
]

# --------------------------------------------------------------------------
# Part B — exam revision. Screen layout, not sheets.
# Weighted by what he actually flagged in the 3 October class.
# No assignment problem is reused; where a technique overlaps, the numbers
# here are different.
# --------------------------------------------------------------------------

PARTB_INTRO = (
    "He said every exam question will be “common” — the same patterns as "
    "class and the slides, sometimes with different numbers. So this half "
    "drills the patterns on fresh numbers. Items he named aloud are flagged."
)

PARTB = [
 ("sec", "heard", "What he said on 3 October"),
 ("p", "From the recording of the last class. Timestamps are in the audio file."),
 ("tbl", ["", "What he said"], [
   ["Syllabus", "Chapters 3, 4, 6 and 8. “Nothing can be skipped” from the slides."],
   ["Format", "Exactly one question set from each of the four chapters."],
   ["Questions", "All will be common. Some numerical problems may carry different values, but the patterns match what was discussed."],
   ["Cut", "Nearest-neighbour / single-linkage clustering is out — he did not teach it."],
   ["Assignment", "Due 28 October, 1–2 days' grace, physical copies to the Section Office."],
   ["Exam", "Wednesday 7 October, 2:00–5:00 PM. Three hours."],
 ]),
 ("flag", "Named for the exam: the Silhouette Coefficient (“পরীক্ষার জন্য পড়তে হবে”), the Hopkins statistic with textbook Example 8.9, and the distance matrix from Chapter 2."),

 ("sec", "hopkins", "Hopkins statistic"),
 ("p", "Tests whether the data has any cluster structure at all, or is just uniformly spread. He told the class to read it, and to read Example 8.9."),
 ("math", "H = Σ xᵢᵈ / ( Σ xᵢᵈ + Σ yᵢᵈ )"),
 ("tbl", ["Term", "Meaning"], [
   ["xᵢ", "Sample n points from the data SPACE. xᵢ is the distance from pᵢ to its nearest neighbour in D."],
   ["yᵢ", "Sample n points from D itself. yᵢ is the distance from qᵢ to its nearest neighbour in D − {qᵢ}."],
   ["d", "The dimensionality of D."],
 ]),
 ("warn", "Getting x and y the wrong way round inverts the answer. x starts from random points in the space; y starts from real points in the data."),
 ("p", "If D is uniform, the two sums are close and H ≈ 0.5. If D is clustered, real points sit closer to each other than random points do, so Σxᵈ is much larger and H approaches 1."),
 ("work", "Example 8.9, worked", [
   "D = {0.9, 1, 1.3, 1.4, 1.5, 1.8, 2, 2.1, 4.1,",
   "     7, 7.4, 7.5, 7.7, 7.8, 7.9, 8.1} in [0, 10].  d = 1",
   "Sampled from D:      1.3, 1.8, 7.5, 7.9",
   "Sampled from space:  1.9, 4, 6, 8",
   "",
   "Σx = |1.9−2| + |4−4.1| + |6−7| + |8−8.1|",
   "   = 0.1 + 0.1 + 1.0 + 0.1  = 1.3",
   "Σy = |1.3−1.4| + |1.8−2| + |7.5−7.4| + |7.9−7.8|",
   "   = 0.1 + 0.2 + 0.1 + 0.1  = 0.5",
   "",
   "H = 1.3 / (1.3 + 0.5) = 1.3 / 1.8 = 0.72",
 ]),
 ("p", "0.72 is well above 0.5, so D has a strong clustering tendency — and indeed it has two clusters, one near 1.5 and one near 7.8."),

 ("sec", "silhouette", "Silhouette coefficient"),
 ("flag", "He worked this on the board and said outright it must be studied for the exam. Expect it with different numbers."),
 ("math", "a(o) = Σ dist(o, o′) / ( |Cᵢ| − 1 )   for o′ ∈ Cᵢ, o′ ≠ o"),
 ("math", "b(o) = min over Cⱼ ≠ Cᵢ of [ Σ dist(o, o′) / |Cⱼ| ]"),
 ("math", "s(o) = ( b(o) − a(o) ) / max{ a(o), b(o) }"),
 ("tbl", ["Detail", "Why it catches people"], [
   ["a(o) divides by |Cᵢ| − 1", "o is not its own neighbour. With 3 points in the cluster you divide by 2, not 3."],
   ["b(o) is a minimum", "Average the distance to EACH other cluster separately, then take the smallest. With only two clusters the min is trivial, which is why the class example hid this step."],
   ["Range is −1 to 1", "Near 1 is compact and well separated. Negative means o is closer to another cluster than its own — a bad assignment."],
 ]),
 ("work", "Fresh practice — three clusters, so the min matters", [
   "C₁ = {a, b, c}   C₂ = {d, e}   C₃ = {f, g}   target o = a",
   "d(a,b)=2  d(a,c)=4",
   "d(a,d)=7  d(a,e)=9     d(a,f)=12  d(a,g)=14",
   "",
   "a(a) = (2 + 4) / (3 − 1) = 6/2 = 3",
   "to C₂: (7 + 9)/2  = 8",
   "to C₃: (12 + 14)/2 = 13",
   "b(a) = min(8, 13) = 8",
   "",
   "s(a) = (8 − 3) / max(3, 8) = 5/8 = 0.625",
 ]),
 ("p", "0.625 is comfortably positive, so a sits well inside its own cluster. Average s(o) over a cluster to score that cluster; average over the whole data set to score the clustering."),

 ("sec", "numclusters", "How many clusters"),
 ("tbl", ["Method", "How it works"], [
   ["Empirical rule", "k ≈ √(n/2) for n points, which leaves about √(2n) points per cluster."],
   ["Elbow method", "Plot within-cluster variance against k. It always falls as k rises, so take the k where the marginal gain drops off — the bend."],
   ["Calinski-Harabasz", "An index that estimates k for k-means directly."],
   ["Cross-validation", "Split the data, cluster one part, measure how well the resulting centres fit the held-out part, repeat over k."],
 ]),
 ("work", "The empirical rule, as he worked it", [
   "n = 20 points",
   "k ≈ √(20 / 2) = √10 = 3.16  →  k = 3",
   "and each cluster then holds about √(2·20) = 6.3 points",
 ]),

 ("sec", "quality", "Measuring clustering quality"),
 ("tbl", ["", "Extrinsic", "Intrinsic"], [
   ["Needs ground truth?", "Yes — supervised", "No — unsupervised"],
   ["Question asked", "How well does the clustering match the known labels?", "How compact and how separated are the clusters?"],
   ["Examples", "Purity, BCubed precision and recall, normalised mutual information", "Silhouette coefficient, Dunn index"],
  ], "lll"),
 ("p", "Dunn uses extreme distances so outliers distort it; silhouette averages, which is why it is the more commonly used of the two."),

 ("sec", "distmatrix", "Distance matrices"),
 ("flag", "Chapter 2 material, but he told the class to revise it because hierarchical clustering is driven entirely by the distance matrix."),
 ("math", "Euclidean:  d(i,j) = √( Σ (xᵢₖ − xⱼₖ)² )"),
 ("math", "Manhattan:  d(i,j) = Σ | xᵢₖ − xⱼₖ |"),
 ("math", "Minkowski:  d(i,j) = ( Σ | xᵢₖ − xⱼₖ |ᵖ )^(1/p)"),
 ("p", "p = 1 gives Manhattan, p = 2 gives Euclidean. The matrix is symmetric with a zero diagonal, so only the lower triangle is ever written out."),

 ("sec", "hier", "Hierarchical clustering"),
 ("warn", "Single linkage (nearest neighbour) is OUT of the syllabus — he said he could not teach it. Complete and average linkage are in."),
 ("tbl", ["", "AGNES", "DIANA"], [
   ["Direction", "Agglomerative, bottom-up", "Divisive, top-down"],
   ["Start", "Every object its own cluster", "All objects in one cluster"],
   ["Each step", "Merge the two closest clusters", "Split the least cohesive cluster"],
   ["Stop", "One cluster remains", "Every object is alone"],
  ], "lll"),
 ("tbl", ["Linkage", "Distance between clusters Cᵢ and Cⱼ"], [
   ["Complete", "The MAXIMUM distance between any point of Cᵢ and any point of Cⱼ. Gives compact, similar-sized clusters; sensitive to outliers."],
   ["Average", "The MEAN over all such pairs. A compromise between the extremes, and more robust."],
   ["Centroid", "The distance between the two cluster centroids."],
 ]),
 ("p", "Neither AGNES nor DIANA can undo a merge or a split, which is why a single bad early step propagates all the way to the root."),

 ("sec", "partition", "k-means and k-medoids"),
 ("work", "k-means on fresh points", [
   "Points (1,1) (2,1) (4,3) (5,4),  k = 2",
   "Initial centres (1,1) and (5,4)",
   "",
   "Round 1",
   "  (1,1): 0    vs 5.00   → C₁",
   "  (2,1): 1.00 vs 4.24   → C₁",
   "  (4,3): 3.61 vs 1.41   → C₂",
   "  (5,4): 5.00 vs 0      → C₂",
   "  new centres (1.5, 1) and (4.5, 3.5)",
   "",
   "Round 2 moves nothing, so it has converged.",
 ]),
 ("tbl", ["", "k-means", "k-medoids (PAM)"], [
   ["Centre is", "The mean — a computed point that need not exist in the data", "A medoid — an actual object of the data set"],
   ["Minimises", "Sum of squared error", "Sum of absolute dissimilarity"],
   ["Outliers", "Drag the mean, so sensitive", "Far more robust"],
   ["Cost per iteration", "O(nkt)", "O(k(n−k)²) — does not scale"],
  ], "lll"),
 ("p", "PAM replaces a medoid with a non-medoid when doing so lowers the total cost. The swap cost is the change in the sum of distances from every object to its nearest representative; swap when that change is negative."),

 ("sec", "patterns", "Pattern mining"),
 ("math", "support(A ⇒ B) = P(A ∪ B)"),
 ("math", "confidence(A ⇒ B) = P(B | A) = support(A ∪ B) / support(A)"),
 ("math", "lift(A, B) = confidence(A ⇒ B) / support(B)"),
 ("work", "Lift on fresh numbers", [
   "1000 transactions. A in 400, B in 500, both in 250.",
   "",
   "support(A∪B) = 250/1000 = 0.25",
   "confidence(A⇒B) = 250/400 = 0.625",
   "lift = 0.625 / 0.50 = 1.25",
 ]),
 ("p", "Lift above 1 means A and B occur together more than chance, so they are positively correlated. Exactly 1 means independent; below 1 means one discourages the other. Confidence alone would have called this a strong rule without telling you B is common anyway."),
 ("work", "Apriori on fresh transactions", [
   "T1{a,b,c}  T2{a,b}  T3{a,c,d}  T4{b,c}",
   "min_sup = 50%, so the minimum count is 2.",
   "",
   "L₁: a:3  b:3  c:3      (d:1 is dropped)",
   "C₂: ab:2  ac:2  bc:2   → all frequent, L₂",
   "C₃: abc appears in T1 only, count 1 → not frequent",
   "",
   "confidence(a⇒b) = 2/3 = 0.67",
 ]),
 ("tbl", ["Term", "Definition"], [
   ["Apriori property", "Every non-empty subset of a frequent itemset is itself frequent. Equivalently, if an itemset is infrequent none of its supersets can be frequent — which is what lets you prune."],
   ["Closed itemset", "Frequent, and no superset has the SAME support."],
   ["Maximal itemset", "Frequent, and no superset is frequent at all."],
   ["Relationship", "Every maximal itemset is closed. Closed itemsets keep the support counts; maximal ones lose them but are fewer."],
 ]),

 ("sec", "classify", "Classification"),
 ("math", "Info(D) = − Σ pᵢ log₂ pᵢ"),
 ("math", "Gain(A) = Info(D) − Info_A(D)"),
 ("math", "GainRatio(A) = Gain(A) / SplitInfo(A)"),
 ("math", "Gini(D) = 1 − Σ pᵢ²"),
 ("work", "All three measures on one fresh split", [
   "D has 10 tuples: 6 yes, 4 no.",
   "Attribute A splits D into",
   "  D₁ = 6 tuples (4 yes, 2 no)",
   "  D₂ = 4 tuples (2 yes, 2 no)",
   "",
   "Info(D)  = −0.6log₂0.6 − 0.4log₂0.4 = 0.9710",
   "Info(D₁) = 0.9183     Info(D₂) = 1.0000",
   "Info_A(D) = 0.6(0.9183) + 0.4(1.0) = 0.9510",
   "Gain(A)   = 0.9710 − 0.9510 = 0.0200",
   "",
   "SplitInfo(A) = −0.6log₂0.6 − 0.4log₂0.4 = 0.9710",
   "GainRatio(A) = 0.0200 / 0.9710 = 0.0206",
   "",
   "Gini(D)  = 1 − (0.6² + 0.4²) = 0.4800",
   "Gini(D₁) = 1 − ((4/6)²+(2/6)²) = 0.4444",
   "Gini(D₂) = 1 − (0.5² + 0.5²)   = 0.5000",
   "Gini_A(D) = 0.6(0.4444) + 0.4(0.5) = 0.4667",
   "ΔGini(A)  = 0.4800 − 0.4667 = 0.0133",
 ]),
 ("p", "Information gain favours attributes with many distinct values; gain ratio divides that bias out with SplitInfo. Gini needs no logarithms, which is why CART uses it, and it always splits binary."),
 ("math", "P(Cᵢ | X) ∝ P(X | Cᵢ) P(Cᵢ) = P(Cᵢ) Π P(xₖ | Cᵢ)"),
 ("p", "Naive Bayes assumes the attributes are conditionally independent given the class. If one conditional probability is zero the whole product is zero, so apply the Laplacian correction: add 1 to every count, and add the number of distinct values to each denominator."),
 ("tbl", ["Measure", "Formula"], [
   ["Accuracy", "(TP + TN) / (TP + TN + FP + FN)"],
   ["Precision", "TP / (TP + FP)"],
   ["Recall, sensitivity", "TP / (TP + FN)"],
   ["Specificity", "TN / (TN + FP)"],
   ["F₁", "2 · precision · recall / (precision + recall)"],
 ]),
 ("work", "Confusion matrix on fresh counts", [
   "TP = 90   FN = 10   FP = 30   TN = 870",
   "",
   "accuracy    = 960/1000 = 0.960",
   "precision   =  90/120  = 0.750",
   "recall      =  90/100  = 0.900",
   "specificity = 870/900  = 0.967",
   "F₁ = 2(0.75)(0.90)/(0.75+0.90) = 0.818",
 ]),
 ("p", "Accuracy reads 96% while precision is only 75%, because the negative class is large. That gap is the whole argument for quoting precision and recall rather than accuracy on imbalanced data."),
 ("tbl", ["", "Eager", "Lazy"], [
   ["Examples", "Decision tree, Bayes, SVM", "k-nearest neighbour"],
   ["Training", "Builds a model up front — slow", "Stores the data — instant"],
   ["Classifying", "Fast", "Slow: compares against the whole training set"],
   ["Fits", "One global model", "Many local approximations"],
  ], "lll"),
 ("p", "kNN needs a value of k and a distance measure, and it needs the attributes normalised first, or whichever attribute has the largest numeric range will dominate the distance."),

 ("sec", "warehouse", "Warehousing and OLAP"),
 ("math", "cuboids = Π Lᵢ   where Lᵢ is the level count of dimension i, counting all"),
 ("work", "Cuboid counting on fresh numbers", [
   "3 dimensions with 4, 3 and 2 levels (all included):",
   "  4 × 3 × 2 = 24 cuboids",
   "",
   "With no hierarchies at all, n dimensions give 2ⁿ:",
   "  5 dimensions → 2⁵ = 32 cuboids",
 ]),
 ("tbl", ["Operation", "What it does"], [
   ["Roll-up", "Climb a hierarchy or drop a dimension, aggregating as you go."],
   ["Drill-down", "The reverse — step down to finer detail."],
   ["Slice", "Fix ONE dimension to a single value."],
   ["Dice", "Fix two or more dimensions, or pick a sub-range of each."],
   ["Pivot", "Rotate the axes to present the same cube differently."],
 ]),
 ("tbl", ["", "OLTP", "OLAP"], [
   ["Purpose", "Day-to-day operations", "Decision support"],
   ["Data", "Current, detailed", "Historical, summarised"],
   ["Design", "Normalised, ER", "Star or snowflake"],
   ["Access", "Short reads and writes", "Long, complex read-mostly queries"],
   ["Unit of work", "Short transactions", "Complex queries over millions of rows"],
  ], "lll"),
 ("tbl", ["Server", "Storage"], [
   ["ROLAP", "Relational tables. Scales to large data, slower queries."],
   ["MOLAP", "A multidimensional array. Fast, but sparse cubes waste space."],
   ["HOLAP", "Both — detail in relational tables, summaries in arrays."],
 ]),
 ("tbl", ["", "Holds"], [
   ["Data warehouse", "Integrated, cleaned, schema-on-write. Built for analysis of known questions."],
   ["Data mart", "A departmental subset of a warehouse."],
   ["Data lake", "Raw data in its native format, schema-on-read. Flexible, but turns into a swamp without governance."],
 ]),

 ("sec", "traps", "Traps"),
 ("tbl", ["Trap", "The right answer"], [
   ["Single linkage", "Not on the syllabus. Do not spend revision time on it."],
   ["a(o) in silhouette", "Divide by |Cᵢ| − 1, not |Cᵢ|."],
   ["b(o) in silhouette", "The MINIMUM of the per-cluster averages, not the average over all other points."],
   ["Hopkins x and y", "x from random space points, y from real data points. H near 1 means clustered, not uniform."],
   ["Rolling up an average", "avg_grade is algebraic. Carry sum and count and divide at the end; never average the averages."],
   ["Cuboid count", "Multiply the level counts. Use 2ⁿ only when there are no hierarchies."],
   ["Apriori pruning", "Prune a candidate when ANY (k−1)-subset is infrequent."],
   ["Naive Bayes zero", "One zero conditional kills the whole class. Say so, then apply Laplace."],
   ["Accuracy on skewed data", "Quote precision, recall and F₁ as well; accuracy alone flatters the majority class."],
 ]),
]
