"""Part B: revision for the final. Theory first, then the maths, per chapter.

Block forms:
    ("chap", id, "Chapter 3", "Data warehousing and OLAP", colour)
    ("sec",  id, "title")
    ("p",    "text, **bold** allowed")
    ("ul",   ["item", ...])            ("ol", ["step", ...])
    ("defs", [("term", "meaning"), ...])
    ("math", "formula")
    ("work", "caption", ["line", ...])  a worked example, monospace
    ("tbl",  heads, rows)  or  ("tbl", heads, rows, {row: "ok"|"no"|"key"})
    ("flag", "text")   he named it for the exam
    ("warn", "text")   a trap that costs marks
    ("tip",  "text")   how to write it in the exam
"""

INTRO = (
    "Four questions, one from each of Chapters 3, 4, 6 and 8. He said every "
    "question will be common: the patterns from class and the slides, "
    "sometimes with new numbers. Each chapter below gives the theory you "
    "write in words, then the calculation worked in full on the slide's own "
    "example. Green rows are kept, red rows are dropped, yellow rows are the "
    "answer."
)

PARTB = [

# ======================================================================
("chap", "exam", "Before you start", "What he said on 3 October", "#5B3E8C"),
("tbl", ["", "From the class recording"], [
  ["Syllabus", "Chapters 3, 4, 6 and 8. “Whatever is in the slides must be read well. Nothing can be skipped.”"],
  ["Format", "One question from each of the four chapters."],
  ["Questions", "All common. Numerical problems may use the slide numbers or slightly different ones."],
  ["Named", "Silhouette coefficient (“must be read for the exam”), the Hopkins statistic with Example 8.9, and the distance matrix from Chapter 2."],
  ["Dropped", "The nearest-neighbour (single-linkage) clustering algorithm. He did not teach it."],
  ["Exam", "Wednesday 7 October, 2:00 to 5:00 PM."],
 ]),

# ======================================================================
("chap", "ch3", "Chapter 3", "Data warehousing and OLAP", "#2B5C8E"),

("sec", "dw-def", "What a data warehouse is"),
("p", "Inmon's definition: **“A data warehouse is a subject-oriented, integrated, time-variant, and nonvolatile collection of data in support of management’s decision-making process.”** Quote it word for word."),
("tbl", ["Property", "Meaning"], [
  ["Subject-oriented", "Organised around major subjects such as customer, product and sales, not around daily operations. Data not useful for decisions is left out."],
  ["Integrated", "Built from several heterogeneous sources: relational databases, flat files, transaction records. Cleaning and integration make names, codes and units consistent. Example: hotel prices in different currencies, with or without tax."],
  ["Time-variant", "Holds history, typically 5 to 10 years. Every key structure contains an element of time, explicitly or implicitly."],
  ["Nonvolatile", "Physically separate from the operational data. No updates happen in place, so it needs no transaction processing, recovery or concurrency control. Only two operations: initial loading and access."],
 ]),
("p", "**Data warehousing** is the process of constructing and using data warehouses."),

("sec", "oltp", "OLTP versus OLAP"),
("tbl", ["Feature", "OLTP (operational DBMS)", "OLAP (data warehouse)"], [
  ["Users", "Clerks, customers", "Managers, analysts (market oriented)"],
  ["Function", "Day-to-day operations: purchasing, banking, payroll", "Data analysis and decision making"],
  ["Data", "Current, detailed", "Historical, consolidated"],
  ["Design", "ER model, application oriented", "Star or snowflake, subject oriented"],
  ["View", "Current, local", "Evolutionary, integrated"],
  ["Access", "Short reads and updates", "Read-only but complex queries"],
 ]),
("p", "**Why keep the warehouse separate?** For performance: the DBMS is tuned for OLTP (indexing, locking, logging), the warehouse for complex OLAP queries. The two also need different data. Decision support needs history, consolidation from many sources, and reconciled data quality, which operational databases do not keep."),

("sec", "arch", "Three-tier architecture and ETL"),
("tbl", ["Tier", "What it holds"], [
  ["Bottom", "The warehouse database server, usually a relational database. Back-end ETL tools feed it from operational and external sources. It also holds the metadata repository."],
  ["Middle", "The OLAP server: ROLAP (extended relational DBMS that maps cube operations to relational ones) or MOLAP (special-purpose server that stores the cube directly)."],
  ["Top", "Front-end client tools for querying, reporting, visualisation, analysis and data mining."],
 ]),
("tbl", ["ETL step", "Job"], [
  ["Extraction", "Get data from multiple, heterogeneous, external sources."],
  ["Cleaning", "Detect errors in the data and fix them where possible."],
  ["Transformation", "Convert from legacy or host format to warehouse format."],
  ["Load", "Sort, summarise, consolidate, compute views, check integrity, build indices and partitions."],
  ["Refresh", "Propagate updates from the sources to the warehouse."],
 ]),
("tbl", ["OLAP server", "Storage", "Trade-off"], [
  ["ROLAP", "Relational tables", "Scales to large data; slower queries"],
  ["MOLAP", "Multidimensional array", "Fast indexing and aggregation; sparse cubes waste space"],
  ["HOLAP", "Both", "Detail in relational tables, aggregates in arrays"],
 ]),

("sec", "cube", "The data cube"),
("defs", [
  ("Dimension", "A perspective the data is viewed by, such as time, item or location. Each has a dimension table, e.g. item(item_name, brand, type)."),
  ("Fact table", "Holds the measures, e.g. dollars_sold and units_sold, and a foreign key to each dimension table."),
  ("Measure", "A numeric function evaluated at each cell. The cell {time = Q1, location = Vancouver, item = computer} holds the sum of all Q1 computer sales in Vancouver."),
  ("Cuboid", "The cube at one combination of dimensions. The n-D cube at the lowest level is the **base cuboid**. The 0-D cuboid holding the single grand total is the **apex cuboid**."),
  ("Lattice", "All cuboids together, from base to apex, form the data cube."),
 ]),
("math", "no hierarchies:    number of cuboids = 2ⁿ"),
("math", "with hierarchies:  number of cuboids = Π (Lᵢ + 1)"),
("p", "Lᵢ is the number of levels of dimension i, **not** counting the virtual top level all. If a question says the levels already include all, just multiply them, as in Problem 3.5(c)."),
("work", "Counting cuboids", [
  "Dimensions time, item, location, no hierarchies:",
  "  2³ = 8 cuboids",
  "  0-D: ()                                   apex",
  "  1-D: (time) (item) (location)",
  "  2-D: (time,item) (time,location) (item,location)",
  "  3-D: (time,item,location)                 base",
  "",
  "With hierarchies:",
  "  time: day < month < quarter < year   L = 4",
  "  item: item_name < type               L = 2",
  "  location: city < country             L = 2",
  "  cuboids = (4+1)(2+1)(2+1) = 5 x 3 x 3 = 45",
 ]),

("sec", "schemas", "Star, snowflake and fact constellation"),
("tbl", ["Schema", "Structure", "Trade-off"], [
  ["Star", "One fact table in the middle, joined to one denormalised table per dimension.", "Few joins, fast queries; some redundancy in dimension tables."],
  ["Snowflake", "A star where some dimension hierarchies are normalised into smaller tables, e.g. item → supplier, location → city.", "Less redundancy, easier to maintain; more joins, slower queries."],
  ["Fact constellation", "Several fact tables share dimension tables, e.g. sales and shipping both use time, item and location. Also called a galaxy schema.", "Models several related processes; more complex."],
 ]),
("tip", "In a schema answer always draw boxes: the fact table in the middle with every foreign key and measure listed, each dimension table with its key first. Problems 3.4(b), 3.5(a) and 3.6(a) in Part A show the full drawings."),

("sec", "hier", "Concept hierarchies and measures"),
("p", "A **concept hierarchy** maps low-level concepts to higher, more general ones. For location: street < city < province_or_state < country. Vancouver and Toronto roll up to Canada; New York and Chicago to USA. Rolling up and drilling down move along these hierarchies."),
("tbl", ["Measure category", "Rule", "Examples"], [
  ["Distributive", "Compute on each partition, then combine the partial results with the same function.", "count, sum, min, max"],
  ["Algebraic", "Computed from a fixed number of distributive values.", "avg = sum / count, standard deviation, min_N"],
  ["Holistic", "No fixed-size summary is enough; needs all the data.", "median, mode, rank"],
 ]),
("warn", "To roll up an average, carry sum and count and divide at the end. Averaging the averages is wrong whenever the groups differ in size."),

("sec", "olap-ops", "OLAP operations"),
("tbl", ["Operation", "What it does", "Example on cube (time, item, location)"], [
  ["Roll-up (drill-up)", "Summarise by climbing a hierarchy or by removing a dimension.", "location from city to country"],
  ["Drill-down (roll-down)", "The reverse: to finer detail, or add a dimension.", "time from quarter to month"],
  ["Slice", "Select on ONE dimension, giving a sub-cube with one fewer dimension.", "time = “Q1”"],
  ["Dice", "Select on TWO OR MORE dimensions.", "location in {Toronto, Vancouver} and time in {Q1, Q2} and item in {computer, phone}"],
  ["Pivot (rotate)", "Reorient the axes to view the data differently, e.g. 3-D to a series of 2-D planes.", "swap item and location axes"],
  ["Drill-across", "Query across more than one fact table.", ""],
  ["Drill-through", "Go below the cube's bottom level to the relational tables, using SQL.", ""],
 ]),
("work", "Writing an OLAP sequence (the exam pattern)", [
  "Cube sales(time, item, location), base cuboid [day, item, street].",
  "Query: total computer sales in each city in 2010.",
  "",
  "1. Roll-up on time from day to year.",
  "2. Roll-up on location from street to city.",
  "3. Dice on year = 2010 and item = \"computer\".",
  "   (or: slice year = 2010, then slice item = \"computer\")",
  "Result: [2010, computer, city], one sum per city.",
 ]),
("tip", "Name the dimension, the operation and the levels: “roll-up on time from day to year”. A bare “roll-up” loses marks."),

# ======================================================================
("chap", "ch4", "Chapter 4", "Pattern mining: Apriori", "#8C5A1E"),

("sec", "fim-def", "Definitions"),
("p", "The slides use one running database. Every example below uses it."),
("tbl", ["TID", "Items"], [
  ["T1", "{pasta, lemon, bread, orange}"],
  ["T2", "{pasta, lemon}"],
  ["T3", "{pasta, orange, cake}"],
  ["T4", "{pasta, lemon, orange, cake}"],
 ]),
("defs", [
  ("Item set I", "All items sold: {pasta, lemon, bread, orange, cake}. It has 2⁵ − 1 = 31 non-empty subsets."),
  ("Transaction", "A set of items with a unique TID. Unordered; each item appears at most once."),
  ("k-itemset", "An itemset of k items. {pasta, lemon} is a 2-itemset."),
  ("Support", "sup(X) = number of transactions containing X. sup({pasta, orange}) = 3, or 75% as a ratio."),
  ("Frequent itemset", "An itemset with support ≥ minsup. Frequent itemset mining lists all of them."),
 ]),
("p", "A higher minsup gives fewer frequent itemsets, and mining becomes faster and needs less memory."),
("math", "support(A ⇒ B)    = P(A ∪ B) = sup(A ∪ B) / |D|"),
("math", "confidence(A ⇒ B) = P(B | A) = sup(A ∪ B) / sup(A)"),
("math", "lift(A, B)          = confidence(A ⇒ B) / support(B)"),
("p", "A rule is **strong** when it meets both min_sup and min_conf. Lift above 1 means A and B are positively correlated; 1 means independent; below 1 means negatively correlated."),

("sec", "apriori-prop", "The Apriori property"),
("p", "**Property 1 (anti-monotone):** if X ⊂ Y then sup(Y) ≤ sup(X). Example: sup({pasta}) = 4, sup({pasta, lemon}) = 3, sup({pasta, lemon, orange}) = 2."),
("p", "**Property 2:** if any subset of Y is infrequent, Y is infrequent. If {bread} is infrequent, {bread, lemon} and every other superset of bread can be skipped without counting."),
("p", "This is what shrinks the search space. The naive approach counts all 2ⁿ − 1 itemsets, reading every transaction for each. On the slide example the naive approach considers 31 itemsets; Apriori considers 18."),

("sec", "apriori-alg", "The Apriori algorithm"),
("ol", [
  "Scan the database to count every 1-itemset (C₁). Keep those with support ≥ minsup (L₁).",
  "**Join:** combine pairs of frequent (k−1)-itemsets into candidate k-itemsets (Cₖ).",
  "**Prune:** delete any candidate with an infrequent (k−1)-subset (Property 2).",
  "**Scan:** count the remaining candidates in the database. Keep those ≥ minsup (Lₖ).",
  "Repeat from step 2 until no candidates can be generated.",
 ]),
("work", "Step 1 and 2: 1-itemsets, minsup = 2", [
  "{pasta}  4   frequent",
  "{lemon}  3   frequent",
  "{bread}  1   infrequent, removed",
  "{orange} 3   frequent",
  "{cake}   2   frequent",
 ]),
("tbl", ["Candidate 2-itemset", "Support", "Result"], [
  ["{pasta, lemon}", "3", "frequent"],
  ["{pasta, orange}", "3", "frequent"],
  ["{pasta, cake}", "2", "frequent"],
  ["{lemon, orange}", "2", "frequent"],
  ["{lemon, cake}", "1", "infrequent"],
  ["{orange, cake}", "2", "frequent"],
 ], {0: "ok", 1: "ok", 2: "ok", 3: "ok", 4: "no", 5: "ok"}),
("p", "Steps 3 to 6: the six pairs come from joining the four frequent items. None has an infrequent subset, so none is pruned before counting. {lemon, cake} fails minsup."),
("tbl", ["Candidate 3-itemset", "Check", "Result"], [
  ["{pasta, lemon, orange}", "all 2-subsets frequent; support 2", "frequent"],
  ["{pasta, lemon, cake}", "{lemon, cake} infrequent", "pruned, never counted"],
  ["{pasta, orange, cake}", "all 2-subsets frequent; support 2", "frequent"],
  ["{lemon, orange, cake}", "{lemon, cake} infrequent", "pruned, never counted"],
 ], {0: "ok", 1: "no", 2: "ok", 3: "no"}),
("p", "Steps 7 to 12: joining the two frequent 3-itemsets gives {pasta, lemon, orange, cake}. Its subset {lemon, orange, cake} is infrequent, so it is pruned. No candidates remain and the algorithm stops."),
("tbl", ["Size", "Frequent itemsets (support)"], [
  ["1", "{pasta}:4, {lemon}:3, {orange}:3, {cake}:2"],
  ["2", "{pasta, lemon}:3, {pasta, orange}:3, {pasta, cake}:2, {lemon, orange}:2, {orange, cake}:2"],
  ["3", "{pasta, lemon, orange}:2, {pasta, orange, cake}:2"],
 ], {0: "key", 1: "key", 2: "key"}),
("p", "**Problems of Apriori:** it can generate a huge number of candidates; it scans the database once per level; and candidates may not exist in the database at all."),

("sec", "rules", "Generating association rules"),
("p", "For each frequent itemset l and each non-empty proper subset s, output s ⇒ (l − s) if sup(l) / sup(s) ≥ min_conf. Support is already known, so no further scan is needed."),
("tbl", ["Rule from {pasta, lemon, orange} (sup 2)", "Confidence", "min_conf 70%"], [
  ["{pasta, lemon} ⇒ {orange}", "2/3 = 67%", "rejected"],
  ["{pasta, orange} ⇒ {lemon}", "2/3 = 67%", "rejected"],
  ["{lemon, orange} ⇒ {pasta}", "2/2 = 100%", "strong"],
  ["{pasta} ⇒ {lemon, orange}", "2/4 = 50%", "rejected"],
  ["{lemon} ⇒ {pasta, orange}", "2/3 = 67%", "rejected"],
  ["{orange} ⇒ {pasta, lemon}", "2/3 = 67%", "rejected"],
 ], {0: "no", 1: "no", 2: "ok", 3: "no", 4: "no", 5: "no"}),
("p", "Support of every rule here is 2/4 = 50%."),

("sec", "closed", "Closed and maximal itemsets"),
("defs", [
  ("Closed", "Frequent, and no proper superset has the same support."),
  ("Maximal", "Frequent, and no proper superset is frequent."),
 ]),
("tbl", ["Itemset", "Support", "Closed?", "Maximal?"], [
  ["{pasta}", "4", "yes", "no"],
  ["{lemon}", "3", "no: {pasta, lemon} also 3", "no"],
  ["{pasta, lemon}", "3", "yes", "no"],
  ["{pasta, orange}", "3", "yes", "no"],
  ["{pasta, cake}", "2", "no: {pasta, orange, cake} also 2", "no"],
  ["{pasta, lemon, orange}", "2", "yes", "yes"],
  ["{pasta, orange, cake}", "2", "yes", "yes"],
 ], {0: "ok", 2: "ok", 3: "ok", 5: "key", 6: "key"}),
("p", "Every maximal itemset is closed. Closed itemsets keep every support count; maximal itemsets are fewer but lose the counts of their subsets."),

("sec", "fp", "FP-growth in brief"),
("ol", [
  "Scan 1: count items, drop the infrequent ones, sort the rest by falling support.",
  "Scan 2: insert each transaction's sorted frequent items as a path in the FP-tree, sharing common prefixes and adding to node counts. A header table links every node of each item.",
  "Mine each item from the bottom of the header table: collect its prefix paths (the conditional pattern base), build a conditional FP-tree from them, and grow patterns recursively.",
 ]),
("p", "FP-growth scans the database twice and generates no candidates. Problem 4.6(a) in Part A works the full tree and compares it with Apriori."),

# ======================================================================
("chap", "ch6", "Chapter 6", "Classification", "#1E6B4F"),

("sec", "cls-basic", "Basic concepts"),
("tbl", ["", "Supervised (classification)", "Unsupervised (clustering)"], [
  ["Training data", "Each tuple has a class label", "No class labels"],
  ["Goal", "Learn a model that labels new data", "Discover classes or clusters in the data"],
 ]),
("p", "**Classification** predicts categorical class labels. **Numeric prediction** models continuous-valued functions. Applications: credit approval, medical diagnosis, fraud detection, web page categorisation."),
("p", "**Two-step process.** (1) Model construction: learn rules, a decision tree or a formula from the training set. (2) Model usage: estimate accuracy on an independent test set, the percentage of test tuples classified correctly. If it is acceptable, classify new tuples. Testing on the training data gives an over-optimistic estimate (overfitting)."),

("sec", "dt", "Decision tree induction"),
("p", "A decision tree is a flowchart-like tree: each internal node tests an attribute, each branch is an outcome of the test, and each leaf holds a class label. The top node is the root."),
("ol", [
  "Start with all training tuples at the root. Attributes are categorical; continuous ones are discretised first.",
  "Pick the test attribute by a selection measure: information gain, gain ratio or Gini index.",
  "Partition the tuples by the attribute's values and recurse on each partition (top-down, greedy, divide and conquer).",
  "Stop when all tuples at a node have one class, or no attributes remain (label the leaf by majority vote), or no tuples remain.",
 ]),
("math", "Info(D)    = − Σ pᵢ log₂ pᵢ"),
("math", "Info_A(D)  = Σ (|Dⱼ| / |D|) × Info(Dⱼ)"),
("math", "Gain(A)    = Info(D) − Info_A(D)"),
("math", "SplitInfo_A(D) = − Σ (|Dⱼ| / |D|) log₂ (|Dⱼ| / |D|)"),
("math", "GainRatio(A)   = Gain(A) / SplitInfo_A(D)"),
("math", "Gini(D)    = 1 − Σ pᵢ²"),
("math", "Gini_A(D)  = (|D₁|/|D|) Gini(D₁) + (|D₂|/|D|) Gini(D₂)"),
("tbl", ["Measure", "Pick", "Note"], [
  ["Information gain (ID3)", "highest gain", "Biased towards attributes with many values."],
  ["Gain ratio (C4.5)", "highest ratio", "Divides out that bias with SplitInfo."],
  ["Gini index (CART)", "lowest Gini_A, i.e. largest reduction", "Binary splits only; no logarithms."],
 ]),
("p", "The slides' training set, buys_computer, 14 tuples: 9 yes, 5 no."),
("tbl", ["age", "income", "student", "credit_rating", "buys"], [
  ["<=30", "high", "no", "fair", "no"],
  ["<=30", "high", "no", "excellent", "no"],
  ["31..40", "high", "no", "fair", "yes"],
  [">40", "medium", "no", "fair", "yes"],
  [">40", "low", "yes", "fair", "yes"],
  [">40", "low", "yes", "excellent", "no"],
  ["31..40", "low", "yes", "excellent", "yes"],
  ["<=30", "medium", "no", "fair", "no"],
  ["<=30", "low", "yes", "fair", "yes"],
  [">40", "medium", "yes", "fair", "yes"],
  ["<=30", "medium", "yes", "excellent", "yes"],
  ["31..40", "medium", "no", "excellent", "yes"],
  ["31..40", "high", "yes", "fair", "yes"],
  [">40", "medium", "no", "excellent", "no"],
 ]),
("work", "Information gain at the root", [
  "Info(D) = −(9/14)log₂(9/14) − (5/14)log₂(5/14) = 0.940",
  "",
  "age:  <=30   5 tuples (2 yes, 3 no)  Info = 0.971",
  "      31..40 4 tuples (4 yes, 0 no)  Info = 0",
  "      >40    5 tuples (3 yes, 2 no)  Info = 0.971",
  "Info_age(D) = (5/14)(0.971) + (4/14)(0) + (5/14)(0.971)",
  "            = 0.694",
  "Gain(age) = 0.940 − 0.694 = 0.246",
  "",
  "Gain(income)        = 0.029",
  "Gain(student)       = 0.151",
  "Gain(credit_rating) = 0.048",
 ]),
("tbl", ["Attribute", "Gain"], [
  ["age", "0.246"], ["student", "0.151"], ["credit_rating", "0.048"], ["income", "0.029"],
 ], {0: "key"}),
("p", "Age has the highest gain, so it is the root. The 31..40 branch is pure (all yes) and becomes a leaf. Under <=30, student gives gain 0.971 and splits it purely. Under >40, credit_rating gives gain 0.971."),
("work", "The resulting tree", [
  "                  age?",
  "        /          |          \\",
  "     <=30       31..40        >40",
  "      |            |            |",
  "  student?        yes     credit_rating?",
  "   /     \\                  /        \\",
  "  no     yes             fair     excellent",
  "  no     yes             yes         no",
 ]),
("work", "Gain ratio and Gini on income", [
  "income splits D into low 4, medium 6, high 4.",
  "SplitInfo = −(4/14)log₂(4/14) − (6/14)log₂(6/14)",
  "            − (4/14)log₂(4/14) = 1.557",
  "GainRatio(income) = 0.029 / 1.557 = 0.019",
  "",
  "Gini(D) = 1 − (9/14)² − (5/14)² = 0.459",
  "Binary split {low, medium} (10: 7 yes, 3 no) vs {high} (4: 2 yes, 2 no)",
  "Gini_income = (10/14)(1 − 0.7² − 0.3²) + (4/14)(1 − 0.5² − 0.5²)",
  "            = (10/14)(0.42) + (4/14)(0.5) = 0.443",
  "The other two splits give 0.458 and 0.450, so {low, medium} | {high} is best.",
 ]),

("sec", "bayes", "Naive Bayesian classification"),
("p", "Bayesian classifiers are statistical: they predict the probability that a tuple belongs to each class. They are fast and accurate on large databases."),
("math", "P(H | X) = P(X | H) P(H) / P(X)      posterior = likelihood × prior / evidence"),
("p", "P(X) is the same for every class, so only P(X | Cᵢ) P(Cᵢ) needs maximising. The **naive** step is class-conditional independence: attributes are assumed independent given the class."),
("math", "P(X | Cᵢ) = Π P(xₖ | Cᵢ) = P(x₁|Cᵢ) × P(x₂|Cᵢ) × … × P(xₙ|Cᵢ)"),
("p", "For a categorical attribute, P(xₖ | Cᵢ) = tuples of Cᵢ with value xₖ, divided by the number of tuples of Cᵢ. For a continuous attribute, use a Gaussian with that class's mean μ and standard deviation σ."),
("work", "Slide example: X = (age <=30, income medium, student yes, credit fair)", [
  "P(yes) = 9/14 = 0.643        P(no) = 5/14 = 0.357",
  "",
  "                       yes            no",
  "P(age <=30 | C)        2/9 = 0.222    3/5 = 0.6",
  "P(income medium | C)   4/9 = 0.444    2/5 = 0.4",
  "P(student yes | C)     6/9 = 0.667    1/5 = 0.2",
  "P(credit fair | C)     6/9 = 0.667    2/5 = 0.4",
  "",
  "P(X|yes) = 0.222 x 0.444 x 0.667 x 0.667 = 0.044",
  "P(X|no)  = 0.6 x 0.4 x 0.2 x 0.4         = 0.019",
  "",
  "P(X|yes)P(yes) = 0.044 x 0.643 = 0.028",
  "P(X|no)P(no)   = 0.019 x 0.357 = 0.007",
  "0.028 > 0.007, so X is classified buys_computer = yes.",
 ]),
("warn", "If one conditional probability is 0, the whole product is 0. Use the Laplacian correction: add 1 to every count and add the number of distinct values to the denominator. Problem 6.7(c) in Part A shows the case."),
("tbl", ["Advantages", "Disadvantages"], [
  ["Easy to implement; good results in most cases.", "Class-conditional independence rarely holds. Dependencies such as symptoms and disease cannot be modelled. Bayesian belief networks handle them."],
 ]),

("sec", "knn", "k-nearest neighbour, eager and lazy"),
("p", "kNN stores the training tuples. To classify X, find the k closest tuples by a distance such as Euclidean, and take the majority class. Normalise attributes first, or the one with the widest range dominates the distance."),
("tbl", ["", "Eager learner", "Lazy learner"], [
  ["Examples", "Decision tree, naive Bayes", "k-nearest neighbour"],
  ["Training", "Builds a model up front, slow", "Just stores the data, fast"],
  ["Classifying", "Fast", "Slow: compares with every stored tuple"],
 ]),

("sec", "eval", "Evaluating a classifier"),
("tbl", ["Measure", "Formula"], [
  ["Accuracy", "(TP + TN) / (P + N)"],
  ["Error rate", "(FP + FN) / (P + N)"],
  ["Sensitivity, recall, TPR", "TP / P = TP / (TP + FN)"],
  ["Specificity", "TN / N = TN / (TN + FP)"],
  ["Precision", "TP / (TP + FP)"],
  ["F₁", "2 × precision × recall / (precision + recall)"],
  ["Fβ", "(1 + β²) × precision × recall / (β² × precision + recall)"],
 ]),
("work", "Confusion matrix", [
  "TP = 90   FN = 10   FP = 30   TN = 870   (P = 100, N = 900)",
  "accuracy    = 960/1000 = 0.960",
  "precision   = 90/120   = 0.750",
  "recall      = 90/100   = 0.900",
  "specificity = 870/900  = 0.967",
  "F₁ = 2(0.75)(0.90) / (0.75 + 0.90) = 0.818",
 ]),
("p", "Accuracy is 96% while precision is 75%. On imbalanced data, quote precision and recall too. An ROC curve plots TPR against FPR as the threshold falls; the area under it (AUC) is 0.5 for random guessing and 1 for a perfect classifier. Problem 6.17 in Part A works one."),

# ======================================================================
("chap", "ch8", "Chapter 8", "Cluster analysis", "#8E2B4F"),

("sec", "cl-basic", "Basic concepts"),
("p", "A **cluster** is a collection of objects similar to one another and dissimilar to objects in other clusters. Clustering is **unsupervised**: no predefined classes. It is used on its own to see the data distribution, or as preprocessing for summarisation, compression (vector quantisation), finding nearest neighbours, and outlier detection."),
("p", "A good clustering has **high intra-class similarity** (cohesive) and **low inter-class similarity** (distinct). Quality depends on the similarity measure, the implementation, and the ability to find hidden patterns."),
("tbl", ["Approach", "Idea", "Methods"], [
  ["Partitioning", "Build k partitions and improve them by a criterion such as sum of squared error.", "k-means, k-medoids, CLARANS"],
  ["Hierarchical", "Build a hierarchical decomposition, bottom-up or top-down.", "AGNES, DIANA, BIRCH, Chameleon"],
  ["Density-based", "Grow clusters while the neighbourhood density is high enough.", "DBSCAN, OPTICS, DENCLUE"],
  ["Grid-based", "Quantise the space into a grid of cells and cluster the cells.", "STING, WaveCluster, CLIQUE"],
 ]),

("sec", "dist", "Distance measures and the distance matrix"),
("math", "Euclidean:  d(i, j) = √( Σ (xᵢ − yᵢ)² )"),
("math", "Manhattan:  d(i, j) = Σ | xᵢ − yᵢ |"),
("math", "Minkowski:  d(i, j) = ( Σ | xᵢ − yᵢ |ᵖ )^(1/p)    p = 1 Manhattan, p = 2 Euclidean"),
("work", "A1(2, 10) to A4(5, 8)", [
  "Euclidean    = √(3² + 2²)       = √13 = 3.61",
  "Manhattan    = |3| + |2|           = 5",
  "Minkowski p3 = (3³ + 2³)^(1/3) = 35^(1/3) = 3.27",
 ]),
("flag", "He asked the class to revise the distance matrix from Chapter 2: hierarchical clustering runs entirely on it. It is an n × n table of d(i, j), symmetric with a zero diagonal, so write only the lower triangle."),

("sec", "kmeans", "k-means"),
("ol", [
  "Place k points in the space as the initial centroids.",
  "Assign each object to the cluster with the closest centroid.",
  "When all objects are assigned, recompute each centroid as the mean of its cluster.",
  "Repeat steps 2 and 3 until the stopping criterion holds.",
 ]),
("p", "**Stopping criteria:** no object changes cluster, or the squared error falls below a small threshold."),
("math", "SE = Σᵢ Σ_{p ∈ Cᵢ} | p − mᵢ |²     mᵢ = mean of cluster Cᵢ"),
("flag", "The slide example uses **Manhattan distance**, not Euclidean. Problem 8.2 in Part A is the same eight points with Euclidean distance. Read the question for which distance to use."),
("p", "Slide problem: cluster A1(2,10) A2(2,5) A3(8,4) A4(5,8) A5(7,5) A6(6,4) A7(1,2) A8(4,9) into three clusters. Initial centres A1(2,10), A4(5,8), A7(1,2). Manhattan distance."),
("tbl", ["Iteration 1", "to (2,10)", "to (5,8)", "to (1,2)", "Cluster"], [
  ["A1 (2,10)", "0", "5", "9", "1"],
  ["A2 (2,5)", "5", "6", "4", "3"],
  ["A3 (8,4)", "12", "7", "9", "2"],
  ["A4 (5,8)", "5", "0", "10", "2"],
  ["A5 (7,5)", "10", "5", "9", "2"],
  ["A6 (6,4)", "10", "5", "7", "2"],
  ["A7 (1,2)", "9", "10", "0", "3"],
  ["A8 (4,9)", "3", "2", "10", "2"],
 ]),
("work", "New centres after iteration 1", [
  "C1 = {A1}                  m1 = (2, 10)",
  "C2 = {A3, A4, A5, A6, A8}  m2 = ((8+5+7+6+4)/5, (4+8+5+4+9)/5) = (6, 6)",
  "C3 = {A2, A7}              m3 = ((2+1)/2, (5+2)/2) = (1.5, 3.5)",
  "",
  "Example: A2 to m1 = |2−2| + |5−10| = 0 + 5 = 5",
 ]),
("tbl", ["Iteration 2", "to (2,10)", "to (6,6)", "to (1.5,3.5)", "Cluster"], [
  ["A1", "0", "8", "7", "1"],
  ["A2", "5", "5", "2", "3"],
  ["A3", "12", "4", "7", "2"],
  ["A4", "5", "3", "8", "2"],
  ["A5", "10", "2", "7", "2"],
  ["A6", "10", "2", "5", "2"],
  ["A7", "9", "9", "2", "3"],
  ["A8", "3", "5", "8", "1"],
 ], {7: "key"}),
("p", "A8 moves to cluster 1. New centres: m1 = ((2+4)/2, (10+9)/2) = (3, 9.5); m2 = ((8+5+7+6)/4, (4+8+5+4)/4) = (6.5, 5.25); m3 = (1.5, 3.5)."),
("tbl", ["Iteration 3", "to (3,9.5)", "to (6.5,5.25)", "to (1.5,3.5)", "Cluster"], [
  ["A1", "1.5", "9.25", "7", "1"],
  ["A2", "5.5", "4.75", "2", "3"],
  ["A3", "10.5", "2.75", "7", "2"],
  ["A4", "3.5", "4.25", "8", "1"],
  ["A5", "8.5", "0.75", "7", "2"],
  ["A6", "8.5", "1.75", "5", "2"],
  ["A7", "9.5", "8.75", "2", "3"],
  ["A8", "1.5", "6.25", "8", "1"],
 ], {3: "key"}),
("p", "A4 moves to cluster 1. New centres: m1 = ((2+5+4)/3, (10+8+9)/3) = (3.67, 9); m2 = ((8+7+6)/3, (4+5+4)/3) = (7, 4.33); m3 = (1.5, 3.5)."),
("tbl", ["Iteration 4", "to (3.67,9)", "to (7,4.33)", "to (1.5,3.5)", "Cluster"], [
  ["A1", "2.67", "10.67", "7", "1"],
  ["A2", "5.67", "5.67", "2", "3"],
  ["A3", "9.33", "1.33", "7", "2"],
  ["A4", "2.33", "5.67", "8", "1"],
  ["A5", "7.33", "0.67", "7", "2"],
  ["A6", "7.33", "1.33", "5", "2"],
  ["A7", "9.67", "8.33", "2", "3"],
  ["A8", "0.33", "7.67", "8", "1"],
 ]),
("tbl", ["Final cluster", "Members", "Centre"], [
  ["1", "A1(2,10), A4(5,8), A8(4,9)", "(3.67, 9)"],
  ["2", "A3(8,4), A5(7,5), A6(6,4)", "(7, 4.33)"],
  ["3", "A2(2,5), A7(1,2)", "(1.5, 3.5)"],
 ], {0: "key", 1: "key", 2: "key"}),
("p", "No object moved in iteration 4, so k-means has converged."),
("tbl", ["k-means: pros", "k-means: cons"], [
  ["Guaranteed to converge, to a local optimum (not necessarily the global one). Low cost: O(nkt) for n objects, k clusters, t iterations.", "k must be specified. Sensitive to noise and outliers, which pull the mean. Sensitive to the initial centroids, so results can differ between runs. Needs a mean, so numeric data."],
 ]),
("p", "**k-medoids (PAM)** uses an actual object, the medoid, as each cluster's centre and minimises the sum of absolute distances. Swap a medoid with a non-medoid whenever the swap lowers the total cost. It is robust to outliers but costs O(k(n−k)²) per iteration."),

("sec", "hclust", "Hierarchical clustering"),
("p", "Groups objects into a tree of clusters. It uses the distance matrix, needs **no k**, but needs a termination condition. No merge or split can be undone, so an early mistake stays."),
("tbl", ["", "Agglomerative (AGNES)", "Divisive (DIANA)"], [
  ["Direction", "Bottom-up, merging", "Top-down, splitting"],
  ["Start", "Each object its own cluster", "All objects in one cluster (the root)"],
  ["Each step", "Merge the two closest clusters", "Split a cluster into smaller ones"],
  ["End", "One cluster, or a termination condition", "Each object alone, or a termination condition"],
 ]),
("work", "The class example: five objects a, b, c, d, e", [
  "AGNES  step 0  {a} {b} {c} {d} {e}",
  "       step 1  {a,b} {c} {d} {e}",
  "       step 2  {a,b} {c} {d,e}",
  "       step 3  {a,b} {c,d,e}",
  "       step 4  {a,b,c,d,e}",
  "",
  "DIANA runs the same steps in reverse:",
  "       {a,b,c,d,e} → {a,b} {c,d,e} → {a,b} {c} {d,e}",
  "       → {a} {b} {c} {d,e} → {a} {b} {c} {d} {e}",
 ]),
("tbl", ["Linkage", "Distance between clusters Cᵢ and Cⱼ"], [
  ["Complete (maximum)", "max |p − p′| over p ∈ Cᵢ, p′ ∈ Cⱼ"],
  ["Average", "mean of |p − p′| over all such pairs"],
  ["Centroid (mean)", "|mᵢ − mⱼ|, the distance between the means"],
  ["Single (minimum)", "min |p − p′|. Excluded from the exam."],
 ]),
("work", "AGNES with complete linkage on a distance matrix", [
  "      a    b    c    d    e",
  "a     0",
  "b     2    0",
  "c     6    5    0",
  "d    10    9    4    0",
  "e     9    8    5    3    0",
  "",
  "Step 1: smallest entry d(a,b) = 2. Merge {a,b}.",
  "  d({a,b},c) = max(6,5)  = 6",
  "  d({a,b},d) = max(10,9) = 10",
  "  d({a,b},e) = max(9,8)  = 9",
  "Step 2: smallest entry d(d,e) = 3. Merge {d,e}.",
  "  d({d,e},c)     = max(4,5)       = 5",
  "  d({d,e},{a,b}) = max(10,9,9,8)  = 10",
  "Step 3: smallest entry 5. Merge c into {c,d,e}.",
  "  d({a,b},{c,d,e}) = max(6,5,10,9,9,8) = 10",
  "Step 4: merge at 10 into {a,b,c,d,e}.",
  "",
  "Merge heights for the dendrogram: 2, 3, 5, 10.",
  "With average linkage the heights are 2, 3, 4.5, 7.83.",
 ]),

("sec", "evaluation", "Evaluation of clustering"),
("p", "Three tasks: **assess clustering tendency** (is there non-random structure at all?), **determine the number of clusters**, and **measure clustering quality**."),

("sec", "hopkins", "Hopkins statistic"),
("flag", "Named in class, together with Example 8.9."),
("ol", [
  "Sample n points p₁ … pₙ uniformly from the data **space**. xᵢ = distance from pᵢ to its nearest neighbour in D.",
  "Sample n points q₁ … qₙ uniformly from **D** without replacement. yᵢ = distance from qᵢ to its nearest neighbour in D − {qᵢ}.",
  "Compute H. d is the dimensionality of D.",
 ]),
("math", "H = Σ xᵢᵈ / ( Σ xᵢᵈ + Σ yᵢᵈ )"),
("p", "If D is uniform, the two sums are close and H ≈ 0.5. If D is clustered, real points lie closer to their neighbours than random points do, so Σxᵈ is much larger and H approaches 1."),
("work", "Example 8.9", [
  "D = {0.9, 1, 1.3, 1.4, 1.5, 1.8, 2, 2.1, 4.1,",
  "     7, 7.4, 7.5, 7.7, 7.8, 7.9, 8.1}, space [0, 10], d = 1",
  "From D (q):      1.3, 1.8, 7.5, 7.9",
  "From space (p):  1.9, 4, 6, 8",
  "",
  "Σx = |1.9−2| + |4−4.1| + |6−7| + |8−8.1|",
  "   = 0.1 + 0.1 + 1 + 0.1 = 1.3",
  "Σy = |1.3−1.4| + |1.8−2| + |7.5−7.4| + |7.9−7.8|",
  "   = 0.1 + 0.2 + 0.1 + 0.1 = 0.5",
  "",
  "H = 1.3 / (1.3 + 0.5) = 1.3 / 1.8 = 0.72",
 ]),
("p", "0.72 is well above 0.5 and close to 1, so D has a strong clustering tendency. It has two clusters, around 1.5 and around 7.8."),
("warn", "x comes from random points in the space, y from real points in D. Swap them and H inverts. Each nearest neighbour is searched in D; for qᵢ, exclude qᵢ itself."),

("sec", "numk", "Determining the number of clusters"),
("tbl", ["Method", "How"], [
  ["Empirical", "k ≈ √(n/2) for n points; each cluster then has about √(2n) points."],
  ["Elbow", "Plot the sum of within-cluster variances var(k) against k. The first or sharpest turning point is the right k."],
  ["Cross-validation", "Split D into m parts. Build the clustering on m − 1 parts and test on the last, e.g. the sum of squared distances from test points to their closest centroid. Repeat for each k and pick the best."],
 ]),
("work", "Empirical method, as worked in class", [
  "n = 20",
  "k ≈ √(20/2) = √10 = 3.16, so k = 3",
  "points per cluster ≈ √(2 × 20) = √40 = 6.3",
 ]),

("sec", "quality", "Measuring clustering quality"),
("tbl", ["", "Extrinsic", "Intrinsic"], [
  ["Ground truth", "Available (supervised)", "Not available (unsupervised)"],
  ["Judges", "How well the clustering matches the ground truth", "How compact the clusters are and how well separated"],
  ["Example", "BCubed precision and recall", "Silhouette coefficient"],
 ]),

("sec", "silhouette", "Silhouette coefficient"),
("flag", "He worked this on the board and said it must be read for the exam. Expect it with new numbers."),
("math", "a(o) = Σ dist(o, o′) / (|Cᵢ| − 1)     o′ ∈ Cᵢ, o′ ≠ o"),
("math", "b(o) = min over Cⱼ ≠ Cᵢ of  Σ dist(o, o′) / |Cⱼ|"),
("math", "s(o) = (b(o) − a(o)) / max{a(o), b(o)}"),
("defs", [
  ("a(o)", "Average distance from o to the other objects of its own cluster. Small means compact."),
  ("b(o)", "Average distance from o to the objects of each other cluster; take the smallest. Large means well separated."),
  ("s(o)", "Between −1 and 1. Near 1: o is well placed. Near 0: o is on a border. Negative: o is closer to another cluster than its own."),
 ]),
("work", "The class example", [
  "Cluster A = {P1, P2, P3}, cluster B = {P4, P5, P6}, o = P1",
  "d(P1,P2) = 2   d(P1,P3) = 4",
  "d(P1,P4) = 8   d(P1,P5) = 9   d(P1,P6) = 10",
  "",
  "a(P1) = (2 + 4) / (3 − 1) = 6/2 = 3",
  "b(P1) = (8 + 9 + 10) / 3 = 27/3 = 9",
  "s(P1) = (9 − 3) / max(3, 9) = 6/9 = 0.667",
 ]),
("p", "0.667 is well above 0.5 and close to 1, so P1 sits well inside cluster A and far from cluster B."),
("work", "With three clusters, where the minimum matters", [
  "C1 = {a, b, c}   C2 = {d, e}   C3 = {f, g}   o = a",
  "d(a,b) = 2   d(a,c) = 4   d(a,d) = 7   d(a,e) = 9",
  "d(a,f) = 12  d(a,g) = 14",
  "",
  "a(a) = (2 + 4) / 2 = 3",
  "to C2: (7 + 9) / 2  = 8",
  "to C3: (12 + 14) / 2 = 13",
  "b(a) = min(8, 13) = 8",
  "s(a) = (8 − 3) / max(3, 8) = 5/8 = 0.625",
 ]),
("p", "Average s(o) over a cluster to judge that cluster, and over all objects to judge the whole clustering."),
("warn", "Divide a(o) by |Cᵢ| − 1, because o is not compared with itself. Take b(o) as the minimum of the per-cluster averages, never the average over all other points."),

("sec", "algos", "k-means, k-medoids, BIRCH, DBSCAN compared"),
("tbl", ["Method", "Cluster shapes", "Inputs", "Main limitation"], [
  ["k-means", "Spherical, convex", "k", "Outliers, initial centres, k fixed"],
  ["k-medoids", "Spherical, convex", "k", "O(k(n−k)²) per iteration"],
  ["BIRCH", "Spherical", "B, threshold T", "Order of input; numeric only"],
  ["DBSCAN", "Arbitrary, with noise", "Eps, MinPts", "Clusters of different density"],
 ]),

# ======================================================================
("chap", "formulas", "Last ten minutes", "Every formula on one screen", "#5B3E8C"),
("tbl", ["Topic", "Formula"], [
  ["Cuboids", "2ⁿ, or Π(Lᵢ + 1) with hierarchies"],
  ["Support", "sup(A ∪ B) / |D|"],
  ["Confidence", "sup(A ∪ B) / sup(A)"],
  ["Lift", "confidence(A ⇒ B) / support(B)"],
  ["Info", "−Σ pᵢ log₂ pᵢ"],
  ["Gain", "Info(D) − Σ (|Dⱼ|/|D|) Info(Dⱼ)"],
  ["Gain ratio", "Gain / SplitInfo"],
  ["Gini", "1 − Σ pᵢ²"],
  ["Naive Bayes", "P(Cᵢ) Π P(xₖ | Cᵢ), pick the largest"],
  ["Accuracy", "(TP + TN) / (P + N)"],
  ["Precision, recall", "TP/(TP + FP), TP/(TP + FN)"],
  ["Euclidean", "√Σ(xᵢ − yᵢ)²"],
  ["Manhattan", "Σ|xᵢ − yᵢ|"],
  ["SSE", "Σᵢ Σ_{p∈Cᵢ} |p − mᵢ|²"],
  ["Hopkins", "Σxᵈ / (Σxᵈ + Σyᵈ), ≈ 0.5 uniform, → 1 clustered"],
  ["Clusters", "k ≈ √(n/2)"],
  ["Silhouette", "(b − a) / max(a, b), a divides by |C| − 1, b is a minimum"],
 ]),
]
